/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.ArrayList;
import java.util.Arrays;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testEmptyArray() {
       ArrayList<Integer> array = new ArrayList<>();
       assertFalse(App.searchTheNumber(array, 1, 0, 3));
    }

    @Test
    public void testNotFound() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(0, 2, 4,8));
       assertFalse(App.searchTheNumber(array, 10, 1, 3));
    }
     
    @Test
    public void testIndexProblem() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(0, 2, 4,8));
       assertFalse(App.searchTheNumber(array, 0, 3, 0));
    } 

    @Test
    public void testNegativeIndex() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(0, 2, 4,8));
       assertFalse(App.searchTheNumber(array, 8, -5, -1));
    } 

    @Test
    public void testFound() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(0, 2, 4,8));
       assertTrue(App.searchTheNumber(array, 4, 0, 3));
    } 

}
