/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    //iki index arasinda aranan'i arama metodu.
    public static boolean searchTheNumber(ArrayList<Integer> array, Integer aranan,
                                          Integer ilk_index, Integer son_index) {
        if(array.size()<=0)
            return false;                                      
        if (ilk_index<0 || son_index<0)
            return false;
        if (son_index<ilk_index)
            return false;
        else{
            for (int i = ilk_index; i <=son_index ; i++) {
                if (array.get(i).equals(aranan))
                    return true;
            }
        }
        return false;
    }
}
